ifndef PREFIX
  PREFIX=/usr/local
endif

install:
	install -Dm755 rofi-surfraw $(DESTDIR)$(PREFIX)/bin/rofi-surfraw
	install -Dm644 searchengines $(DESTDIR)$(PREFIX)/usr/share/doc/searchengines
	install -Dm644 config $(DESTDIR)$(PREFIX)/etc/rofi-surfraw.conf

