#!/bin/bash

# source surfraw config
source $HOME/.surfraw.conf

# get list of search engines from surfraw
if [[ $@ == *"--no-list"* ]]; then
    :
else
    list=$(sr -elvi | awk '{ print $1 }' | tail -n +2)
fi

# get custom engines from text file
if [[ $@ == *"--no-custom"* ]]; then
    :
else
    custom=$(cat $HOME/.config/rofi-surfraw/searchengines | awk -F '-' '{ print $3,$1 }' | cut -c 2-)
fi

main () {
# Draw Menu
elvi=$(echo -e "${list}\n${custom}" | rofi -dmenu -mesg "Entries begining with "!" are custom bangs" -p "Select Search Provider > ")

# Some logic
if [[ $elvi == "" ]]; then exit
elif [[ $elvi == "!"* ]]; then
    entry=$(grep "$(echo "${elvi}" | awk '{ print $1 }')" "$HOME/.config/rofi-surfraw/searchengines")
    method=$(echo "${entry}" | awk -F ' - ' '{ print $2 }')
    bang=$(echo "${entry}" | awk -F ' - ' '{ print $4 }')
    search=$(echo "${elvi}" | awk '{$1=""; print $0}' | cut -c 2-)
    if [[ $method == "surfraw" ]]; then
        sr ${bang} ${search}
    elif [[ $method == "custom" ]]; then
        "$SURFRAW_graphical_browser" ${bang}"${search}"
    fi
else
    name=$(echo "${elvi}" | awk '{ print $1 }')
    search=$(echo "${elvi}" | awk '{$1=""; print $0}' | cut -c 2-)
    sr ${name} ${search}
fi
}

if [[ $1 == "--help" ]]; then
    echo "rofi-surfraw - (C) 2015 Rasmus Steinke <rasi at xssn dot at>"
    echo "---"
    echo "--help         this help"
    echo "--no-list      do not show inbuild search engines"
    echo "--no-custom    do not show custom search engines"
else
    main
fi
