#!/bin/bash

# source surfraw config
source $HOME/.surfraw.conf

# get list of search engines from surfraw
if [[ $1 == "--no-list" ]]; then
    :
else
    list=$(sr -elvi | tail -n +2)
fi

# get custom engines from text file
custom=$(cat $HOME/.config/rofi-surfraw/searchengines | awk -F '-' '{ print $3,$1 }' | cut -c 2-)

# Draw Menu
elvi=$(echo -e "${list}\n${custom}" | rofi -dmenu -mesg "Entries begining with "*" are custom engines" -p "Select Search Provider > ")

# Some logic
if [[ $elvi == "" ]]; then exit
elif [[ $elvi == "* "* ]]; then
    name=$(grep "$(echo "${elvi}" | cut -c 3-)" "$HOME/.config/rofi-surfraw/searchengines" | awk -F ' - ' '{ print $1 }')
    method=$(grep "$(echo "${elvi}" | cut -c 3-)" "$HOME/.config/rofi-surfraw/searchengines" | awk -F ' - ' '{ print $2 }')
    bang=$(grep "$(echo "${elvi}" | cut -c 3-)" "$HOME/.config/rofi-surfraw/searchengines" | awk -F ' - ' '{ print $4 }')
    if [[ $method == "surfraw" ]]; then
        searchmenu=$(echo "" | rofi -dmenu -mesg "Using ${name}" -p "> ")
        if [[ $searchmenu == "" ]]; then
            exit
        fi
        sr ${bang} ${searchmenu}
    elif [[ $method == "custom" ]]; then
        searchmenu=$(echo "" | rofi -dmenu -mesg "Using ${name}" -p "> ")
        if [[ $searchmenu == "" ]]; then
            exit
        fi
        "$SURFRAW_graphical_browser" ${bang}"${searchmenu}"
    fi
elif [[ $elvi == "!"* ]]; then
    entry=$(grep "$(echo "${elvi}" | awk '{ print $1 }')" "$HOME/.config/rofi-surfraw/searchengines")
    method=$(echo "${entry}" | awk -F ' - ' '{ print $2 }')
    bang=$(echo "${entry}" | awk -F ' - ' '{ print $4 }')
    search=$(echo "${elvi}" | awk '{$1=""; print $0}' | cut -c 2-)
    if [[ $method == "surfraw" ]]; then
        sr ${bang} ${search}
    elif [[ $method == "custom" ]]; then
        "$SURFRAW_graphical_browser" ${bang}"${search}"
    fi
else
    name=$(echo "${elvi}" | awk '{ print $1 }')
    searchmenu=$(echo "" | rofi -dmenu -mesg "Using ${name}" -p "> ")
    if [[ $searchmenu == "" ]]; then
        exit
    fi
    sr ${name} ${searchmenu}
fi
